name: softnet_school_portal
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  get_it: ^7.7.0
  internet_connection_checker: ^2.0.0
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.2.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  awesome_snackbar_content: ^0.1.4
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  
  
